# TCL File Generated by Component Editor 13.0
# Wed Jul 10 19:20:06 JST 2013
# DO NOT MODIFY


# 
# vga_component "vga_component" v1.1
# S.OSAFUNE / J-7SYSTEM Works 2013.07.10.19:20:06
# 
# 

# 
# request TCL package from ACDS 13.0
# 
package require -exact qsys 13.0


# 
# module vga_component
# 
set_module_property DESCRIPTION ""
set_module_property NAME vga_component
set_module_property VERSION 1.1
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP Peripherals/Display
set_module_property AUTHOR "S.OSAFUNE / J-7SYSTEM Works"
set_module_property DISPLAY_NAME vga_component
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset quartus_synth QUARTUS_SYNTH "" "Quartus Synthesis"
set_fileset_property quartus_synth TOP_LEVEL vga_component
set_fileset_property quartus_synth ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file vga_component.vhd VHDL PATH vga_component.vhd TOP_LEVEL_FILE
add_fileset_file vga_avm.vhd VHDL PATH vga_avm.vhd
add_fileset_file vga_linebuffer.vhd VHDL PATH vga_linebuffer.vhd
add_fileset_file vga_syncgen.vhd VHDL PATH vga_syncgen.vhd

add_fileset sim_vhdl SIM_VHDL "" "VHDL Simulation"
set_fileset_property sim_vhdl TOP_LEVEL vga_component
set_fileset_property sim_vhdl ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file vga_component.vhd VHDL PATH vga_component.vhd
add_fileset_file vga_avm.vhd VHDL PATH vga_avm.vhd
add_fileset_file vga_linebuffer.vhd VHDL PATH vga_linebuffer.vhd
add_fileset_file vga_syncgen.vhd VHDL PATH vga_syncgen.vhd


# 
# parameters
# 
add_parameter LINEOFFSETBYTES INTEGER 2048 ""
set_parameter_property LINEOFFSETBYTES DEFAULT_VALUE 2048
set_parameter_property LINEOFFSETBYTES DISPLAY_NAME LINEOFFSETBYTES
set_parameter_property LINEOFFSETBYTES TYPE INTEGER
set_parameter_property LINEOFFSETBYTES UNITS None
set_parameter_property LINEOFFSETBYTES ALLOWED_RANGES -2147483648:2147483647
set_parameter_property LINEOFFSETBYTES DESCRIPTION ""
set_parameter_property LINEOFFSETBYTES HDL_PARAMETER true
add_parameter H_TOTAL INTEGER 800
set_parameter_property H_TOTAL DEFAULT_VALUE 800
set_parameter_property H_TOTAL DISPLAY_NAME H_TOTAL
set_parameter_property H_TOTAL TYPE INTEGER
set_parameter_property H_TOTAL UNITS None
set_parameter_property H_TOTAL ALLOWED_RANGES -2147483648:2147483647
set_parameter_property H_TOTAL HDL_PARAMETER true
add_parameter H_SYNC INTEGER 96
set_parameter_property H_SYNC DEFAULT_VALUE 96
set_parameter_property H_SYNC DISPLAY_NAME H_SYNC
set_parameter_property H_SYNC TYPE INTEGER
set_parameter_property H_SYNC UNITS None
set_parameter_property H_SYNC ALLOWED_RANGES -2147483648:2147483647
set_parameter_property H_SYNC HDL_PARAMETER true
add_parameter H_BACKP INTEGER 48
set_parameter_property H_BACKP DEFAULT_VALUE 48
set_parameter_property H_BACKP DISPLAY_NAME H_BACKP
set_parameter_property H_BACKP TYPE INTEGER
set_parameter_property H_BACKP UNITS None
set_parameter_property H_BACKP ALLOWED_RANGES -2147483648:2147483647
set_parameter_property H_BACKP HDL_PARAMETER true
add_parameter H_ACTIVE INTEGER 640
set_parameter_property H_ACTIVE DEFAULT_VALUE 640
set_parameter_property H_ACTIVE DISPLAY_NAME H_ACTIVE
set_parameter_property H_ACTIVE TYPE INTEGER
set_parameter_property H_ACTIVE UNITS None
set_parameter_property H_ACTIVE ALLOWED_RANGES -2147483648:2147483647
set_parameter_property H_ACTIVE HDL_PARAMETER true
add_parameter V_TOTAL INTEGER 525
set_parameter_property V_TOTAL DEFAULT_VALUE 525
set_parameter_property V_TOTAL DISPLAY_NAME V_TOTAL
set_parameter_property V_TOTAL TYPE INTEGER
set_parameter_property V_TOTAL UNITS None
set_parameter_property V_TOTAL ALLOWED_RANGES -2147483648:2147483647
set_parameter_property V_TOTAL HDL_PARAMETER true
add_parameter V_SYNC INTEGER 2
set_parameter_property V_SYNC DEFAULT_VALUE 2
set_parameter_property V_SYNC DISPLAY_NAME V_SYNC
set_parameter_property V_SYNC TYPE INTEGER
set_parameter_property V_SYNC UNITS None
set_parameter_property V_SYNC ALLOWED_RANGES -2147483648:2147483647
set_parameter_property V_SYNC HDL_PARAMETER true
add_parameter V_BACKP INTEGER 33
set_parameter_property V_BACKP DEFAULT_VALUE 33
set_parameter_property V_BACKP DISPLAY_NAME V_BACKP
set_parameter_property V_BACKP TYPE INTEGER
set_parameter_property V_BACKP UNITS None
set_parameter_property V_BACKP ALLOWED_RANGES -2147483648:2147483647
set_parameter_property V_BACKP HDL_PARAMETER true
add_parameter V_ACTIVE INTEGER 480
set_parameter_property V_ACTIVE DEFAULT_VALUE 480
set_parameter_property V_ACTIVE DISPLAY_NAME V_ACTIVE
set_parameter_property V_ACTIVE TYPE INTEGER
set_parameter_property V_ACTIVE UNITS None
set_parameter_property V_ACTIVE ALLOWED_RANGES -2147483648:2147483647
set_parameter_property V_ACTIVE HDL_PARAMETER true


# 
# display items
# 


# 
# connection point ext
# 
add_interface ext conduit end
set_interface_property ext associatedClock ""
set_interface_property ext associatedReset ""
set_interface_property ext ENABLED true
set_interface_property ext EXPORT_OF ""
set_interface_property ext PORT_NAME_MAP ""
set_interface_property ext SVD_ADDRESS_GROUP ""

add_interface_port ext video_clk export Input 1
add_interface_port ext video_rout export Output 5
add_interface_port ext video_gout export Output 5
add_interface_port ext video_bout export Output 5
add_interface_port ext video_hsync_n export Output 1
add_interface_port ext video_vsync_n export Output 1
add_interface_port ext video_enable export Output 1


# 
# connection point m1
# 
add_interface m1 avalon start
set_interface_property m1 addressUnits SYMBOLS
set_interface_property m1 associatedClock m_clk
set_interface_property m1 associatedReset g_reset
set_interface_property m1 bitsPerSymbol 8
set_interface_property m1 burstOnBurstBoundariesOnly false
set_interface_property m1 burstcountUnits WORDS
set_interface_property m1 doStreamReads false
set_interface_property m1 doStreamWrites false
set_interface_property m1 holdTime 0
set_interface_property m1 linewrapBursts false
set_interface_property m1 maximumPendingReadTransactions 0
set_interface_property m1 readLatency 0
set_interface_property m1 readWaitTime 1
set_interface_property m1 setupTime 0
set_interface_property m1 timingUnits Cycles
set_interface_property m1 writeWaitTime 0
set_interface_property m1 ENABLED true
set_interface_property m1 EXPORT_OF ""
set_interface_property m1 PORT_NAME_MAP ""
set_interface_property m1 SVD_ADDRESS_GROUP ""

add_interface_port m1 avm_m1_address address Output 32
add_interface_port m1 avm_m1_waitrequest waitrequest Input 1
add_interface_port m1 avm_m1_burstcount burstcount Output 10
add_interface_port m1 avm_m1_read read Output 1
add_interface_port m1 avm_m1_readdata readdata Input 32
add_interface_port m1 avm_m1_readdatavalid readdatavalid Input 1


# 
# connection point s1
# 
add_interface s1 avalon end
set_interface_property s1 addressAlignment NATIVE
set_interface_property s1 addressUnits WORDS
set_interface_property s1 associatedClock s_clk
set_interface_property s1 associatedReset g_reset
set_interface_property s1 bitsPerSymbol 8
set_interface_property s1 burstOnBurstBoundariesOnly false
set_interface_property s1 burstcountUnits WORDS
set_interface_property s1 explicitAddressSpan 0
set_interface_property s1 holdTime 0
set_interface_property s1 linewrapBursts false
set_interface_property s1 maximumPendingReadTransactions 0
set_interface_property s1 readLatency 0
set_interface_property s1 readWaitTime 1
set_interface_property s1 setupTime 0
set_interface_property s1 timingUnits Cycles
set_interface_property s1 writeWaitTime 0
set_interface_property s1 ENABLED true
set_interface_property s1 EXPORT_OF ""
set_interface_property s1 PORT_NAME_MAP ""
set_interface_property s1 SVD_ADDRESS_GROUP ""

add_interface_port s1 avs_s1_address address Input 2
add_interface_port s1 avs_s1_read read Input 1
add_interface_port s1 avs_s1_readdata readdata Output 32
add_interface_port s1 avs_s1_write write Input 1
add_interface_port s1 avs_s1_writedata writedata Input 32
set_interface_assignment s1 embeddedsw.configuration.isFlash 0
set_interface_assignment s1 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment s1 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment s1 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point irq
# 
add_interface irq interrupt end
set_interface_property irq associatedAddressablePoint s1
set_interface_property irq associatedClock s_clk
set_interface_property irq associatedReset g_reset
set_interface_property irq ENABLED true
set_interface_property irq EXPORT_OF ""
set_interface_property irq PORT_NAME_MAP ""
set_interface_property irq SVD_ADDRESS_GROUP ""

add_interface_port irq irq_s1 irq Output 1


# 
# connection point s_clk
# 
add_interface s_clk clock end
set_interface_property s_clk clockRate 0
set_interface_property s_clk ENABLED true
set_interface_property s_clk EXPORT_OF ""
set_interface_property s_clk PORT_NAME_MAP ""
set_interface_property s_clk SVD_ADDRESS_GROUP ""

add_interface_port s_clk s1_clk clk Input 1


# 
# connection point m_clk
# 
add_interface m_clk clock end
set_interface_property m_clk clockRate 0
set_interface_property m_clk ENABLED true
set_interface_property m_clk EXPORT_OF ""
set_interface_property m_clk PORT_NAME_MAP ""
set_interface_property m_clk SVD_ADDRESS_GROUP ""

add_interface_port m_clk m1_clk clk Input 1


# 
# connection point g_reset
# 
add_interface g_reset reset end
set_interface_property g_reset associatedClock s_clk
set_interface_property g_reset synchronousEdges DEASSERT
set_interface_property g_reset ENABLED true
set_interface_property g_reset EXPORT_OF ""
set_interface_property g_reset PORT_NAME_MAP ""
set_interface_property g_reset SVD_ADDRESS_GROUP ""

add_interface_port g_reset g_reset reset Input 1

